# This file was generated by GoReleaser. DO NOT EDIT.
cask "cfl" do
  name "cfl"
  desc "Command-line interface for Atlassian Confluence"
  homepage "https://github.com/rianjs/confluence-cli"
  version "0.7.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cfl"

  on_macos do
    on_intel do
      url "https://github.com/rianjs/confluence-cli/releases/download/v#{version}/cfl_#{version}_darwin_amd64.tar.gz"
      sha256 "a9fe1edf1ee90af4478483a5d89f43c8fe0767dad7069275b835fb1010f96d8c"
    end
    on_arm do
      url "https://github.com/rianjs/confluence-cli/releases/download/v#{version}/cfl_#{version}_darwin_arm64.tar.gz"
      sha256 "777c4430e3b1a847b4a64e0b7c1d102a35b896f14a80a6a627e10c881061857d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rianjs/confluence-cli/releases/download/v#{version}/cfl_#{version}_linux_amd64.tar.gz"
      sha256 "880527bb28bb39253e3e5a035dfadad41f127877083cc87834024919d608dfb8"
    end
    on_arm do
      url "https://github.com/rianjs/confluence-cli/releases/download/v#{version}/cfl_#{version}_linux_arm64.tar.gz"
      sha256 "b91f382d61a5f9d121f5e76ff7a28b582e723d71e28638ee5665d548b397d69f"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cfl"]
  end

  caveats do
    "cfl has been installed. Run 'cfl init' to configure."
  end

  # No zap stanza required
end
