# This file was generated by GoReleaser. DO NOT EDIT.
cask "cfl" do
  name "cfl"
  desc "Command-line interface for Atlassian Confluence"
  homepage "https://github.com/rianjs/confluence-cli"
  version "0.2.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cfl"

  on_macos do
    on_intel do
      url "https://github.com/rianjs/confluence-cli/releases/download/v#{version}/cfl_#{version}_darwin_amd64.tar.gz"
      sha256 "25a91518056da32ecf8373afeb8c67df068f8c8591a0a551fac3f491a18f0ef0"
    end
    on_arm do
      url "https://github.com/rianjs/confluence-cli/releases/download/v#{version}/cfl_#{version}_darwin_arm64.tar.gz"
      sha256 "8dd5812d47e6e113884ba05ab98fd4cabcd04159b27d3d809b0aaa1722b6f1d1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rianjs/confluence-cli/releases/download/v#{version}/cfl_#{version}_linux_amd64.tar.gz"
      sha256 "f071c385b711478d41720fe7db37eb294781ce31e13fa347999d25e2b24b0b85"
    end
    on_arm do
      url "https://github.com/rianjs/confluence-cli/releases/download/v#{version}/cfl_#{version}_linux_arm64.tar.gz"
      sha256 "bc86acbd0a825f547e1819c4996b3b0d06f484df3aebe688f58143c9a074745e"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cfl"]
  end

  caveats do
    "cfl has been installed. Run 'cfl init' to configure."
  end

  # No zap stanza required
end
